services:
  - name: frontend
    buildCommand: npm run build
    startCommand: PORT=3000 npm run start:client
    env:
      - key: NODE_ENV
        value: production

  - name: backend
    startCommand: PORT=8080 npm run start:server
    env:
      - key: NODE_ENV
        value: production
